# Generated by Django 3.2.8 on 2021-10-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecondTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer_true', models.CharField(blank=True, max_length=100, null=True)),
                ('answer_1', models.CharField(blank=True, max_length=100, null=True)),
                ('answer_2', models.CharField(blank=True, max_length=100, null=True)),
                ('answer_3', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
