# Generated by Django 3.2.8 on 2021-10-15 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_task', models.IntegerField(choices=[(1, 'NOSTANDART TOPSHIRIQ'), (2, 'MANTIQIY SAVOLLAR'), (3, 'KREATIV FIKRLASH')], default=0)),
                ('last_score', models.IntegerField(blank=True, default=0, null=True)),
                ('max_score', models.IntegerField(blank=True, default=0, null=True)),
                ('avarage_score', models.IntegerField(blank=True, default=0, null=True)),
                ('attempt', models.IntegerField(blank=True, default=0, null=True)),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
